name: SlardcraftPlugin
main: slard.craft.SlardcraftPlugin
version: 1.0
api-version: 1.18
commands:
  setradius:
      description: Sets the radius of the border around world spawn
      usage: /<command> <arg>